<!doctype html>
<html lang="es">
	<head>
		<meta charset="utf-8" />
	   <!-- Always force latest IE rendering engine (even in intranet) & Chrome Frame -->
	   <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
	   <!-- Mobile viewport optimized: h5bp.com/viewport -->
	   <meta name="viewport" content="width=device-width">
		<title>Blog</title>

		 <link href='http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700' rel='stylesheet' type='text/css'>
	   <link rel="stylesheet" type="text/css" href="<?php echo Conection::route();?>public/content/css/bootstrap.css">
	   <link rel="stylesheet" type="text/css" href="<?php echo Conection::route();?>public/content/css/bootstrap-responsive.css">
	   <link rel="stylesheet" type="text/css" href="<?php echo Conection::route();?>public/content/css/bootmetro.css">
	   <link rel="stylesheet" type="text/css" href="<?php echo Conection::route();?>public/content/css/bootmetro-tiles.css">
	   <link rel="stylesheet" type="text/css" href="<?php echo Conection::route();?>public/content/css/bootmetro-charms.css">
	   <link rel="stylesheet" type="text/css" href="<?php echo Conection::route();?>public/content/css/metro-ui-light.css">
	   <link rel="stylesheet" type="text/css" href="<?php echo Conection::route();?>public/content/css/icomoon.css">
	   <link rel="stylesheet" type="text/css" href="<?php echo Conection::route();?>public/css/style.css">
	   <link rel="stylesheet" type="text/css" href="<?php echo Conection::route();?>public/content/css/demo.css">
	   <link rel="stylesheet" type="text/css" href="<?php echo Conection::route();?>public/scripts/google-code-prettify/prettify.css" >
   	   <link rel="shortcut icon" href="<?php echo Conection::route();?>public/content/ico/favicon.ico">
   	   <link rel="stylesheet" type="text/css" href="<?php echo Conection::route();?>public/css/blog.css">

	</head>

	<body>

           <!-- ****menu**** -->
            <?php include("menu.phtml"); ?>
            <?php include("loginModal.phtml"); ?>
           <!-- ****menu**** -->

     <div class="container-fluid">
       	<div class="row-fluid">
       		<div class="span12">

                <!-- *********content********* -->
                <!-- <div class="row"> -->
                <div class="span8">
                <?php for ($i=0; $i <10 ; $i++) {

                     ?>
		               <div class="contetn">
		                  <div class="images-content">
		                  	<img src="<?php echo Conection::route();?>public/img/sublic.jpg" alt="">
		                  </div>

		                  <div class="title-content">
		                  	<h1>
		                  		<a href="#">Titulo de la noticia</a>
		                  	</h1>
		                  </div>

		                  <div class="det-content">
		                  	<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores, autem, eligendi quo provident quis nihil delectus earum quisquam incidunt maxime illo atque facilis vitae. Aut rem voluptatem eius ducimus voluptas.
		                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facilis, odit, enim esse reiciendis est assumenda optio ab dolorum praesentium ipsa perferendis eos consequuntur voluptatibus autem id dicta sequi delectus deserunt!</p>

		                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores, autem, eligendi quo provident quis nihil delectus earum quisquam incidunt maxime illo atque facilis vitae. Aut rem voluptatem eius ducimus voluptas.
		                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facilis, odit, enim esse reiciendis est assumenda optio ab dolorum praesentium ipsa perferendis eos consequuntur voluptatibus autem id dicta sequi delectus deserunt!</p>
		                  </div>

		                  <div class="dat-auth">
		                    <i class="icon-calendar icon-cont"></i><small>23 May 2013</small> <i class="icon-user icon-cont"></i><small>Oriol Rivera</small>
		                  </div>

		                  <div class="read">
		                  	<a href="#" class="btn btn-primary">Leer Más <i class="icon-arrow-right-3"></i> </a>
		                  </div>
		              </div>

               <?php } ?>
                </div><!-- end span8 -->
                <!-- </div> -->
                <!-- *********content********* -->

                <!-- **********sidebar************** -->
                <div class="span4">
                    <ul class="nav nav-list">
						<li class="nav-header">social</li>
						<li class="divider"></li>
				    </ul>
                    <div class="link-non">
						<a href="#" class="fs1" aria-hidden="true" data-icon="&#xe0a5;" title="Síguenos en GitHub"></a>
						<a href="#" class="fs1" aria-hidden="true" data-icon="&#xe090;" title="Síguenos en facebook"></a>
						<a href="#" class="fs1" aria-hidden="true" data-icon="&#xe092;" title="Síguenos en twitter"></a>
						<a href="#" class="fs1" aria-hidden="true" data-icon="&#xe08e;" title="Síguenos en google +"></a>
						<a href="#" class="fs1" aria-hidden="true" data-icon="&#xe097;" title="Síguenos en youtube"></a>
				    </div>

                	<ul class="nav nav-list">
                		<li class="divider"></li>
						<li class="nav-header">CATEGORIAS</li>
						<li><a href="#">Categoria 1</a></li>
						<li><a href="#">Categoria 2</a></li>
						<li><a href="#">Categoria 3</a></li>
						<li><a href="#">Categoria 4</a></li>
						<li><a href="#">Categoria 5</a></li>
						<li><a href="#">Categoria 6</a></li>
						<li><a href="#">Categoria 7</a></li>
						<li><a href="#">Categoria 7</a></li>
						<li class="divider"></li>
					</ul>

					<ul class="nav nav-list">
						<li class="nav-header">Ultimas publicaciones</li>
						<li><a href="">Titulo de la publicación</a></li>
						<li><a href="">Titulo de la publicación</a></li>
						<li><a href="">Titulo de la publicación</a></li>
						<li><a href="">Titulo de la publicación</a></li>
						<li><a href="">Titulo de la publicación</a></li>

						<li class="divider"></li>

                        <li class="nav-header">Twitter</li>
						<li><a class="twitter-timeline" href="https://twitter.com/sheol1" data-widget-id="305042318153621505">Tweets por @sheol1</a></li>

						<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");
						</script>

						<li class="divider"></li>
					</ul>

                </div> <!-- end span4 -->
                <!-- ***************sidebar************** -->


       		</div>
       		<!-- ******paginacion*********** -->
       		  <div class="pagination">
				<ul>
					<li><a href="#">Prev</a></li>
					<li><a href="#">1</a></li>
					<li><a href="#">2</a></li>
					<li><a href="#">3</a></li>
					<li><a href="#">4</a></li>
					<li><a href="#">Next</a></li>
				</ul>
			</div>

       		<!-- ******paginacion*********** -->
       	</div>
       </div>



      <div id="push"></div>
	 <!-- **********footer********************** -->

	   <?php include("footer.phtml"); ?>

	  <!-- **********footer********************** -->


	   <!-- Grab Google CDN's jQuery. fall back to local if necessary -->
	   <script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
	   <script>window.jQuery || document.write("<script src='<?php echo Conection::route();?>public/scripts/jquery-1.8.2.min.js'>\x3C/script>")</script>



	   <script type="text/javascript" src="<?php echo Conection::route();?>public/scripts/google-code-prettify/prettify.js"></script>
	   <script type="text/javascript" src="<?php echo Conection::route();?>public/scripts/jquery.mousewheel.js"></script>
	   <script type="text/javascript" src="<?php echo Conection::route();?>public/scripts/jquery.scrollTo.js"></script>
	   <script type="text/javascript" src="<?php echo Conection::route();?>public/scripts/bootstrap.min.js"></script>
	   <script type="text/javascript" src="<?php echo Conection::route();?>public/scripts/bootmetro.js"></script>
	   <script type="text/javascript" src="<?php echo Conection::route();?>public/scripts/bootmetro-charms.js"></script>
	   <script type="text/javascript" src="<?php echo Conection::route();?>public/scripts/demo.js"></script>
	   <script type="text/javascript" src="<?php echo Conection::route();?>public/scripts/holder.js"></script>

	   <script type="text/javascript">
	      $(".metro").metro();
	   </script>
	</body>
</html>