<html>
<head>
	<title>ERROR 404</title>


        <style type="text/css">
              body{
              background-repeat: no-repeat;


              }

              #princil{
                    background-image:url("http://life-virtual.com/public/img/404.jpg");
                    height: 380px;
                    margin: 0 auto;
                    width: 570px;
              }

              #text{

                text-align: center;

              }


        </style>


</head>
<body>


	<div id="princil">


	</div>
	 <div id="text"><h1>Bien hecho, la rompiste.</h1>
       <p>Esta web no existe o hubo un error horrible.</p>
	</div>
	<div id="text"><a href="<?php echo Conection::route();?>">Salir de aqui</a></div>


</body>
</html>