<div class="navbar navbar-inverse navbar-fixed-top">
         	<div class="navbar-inner">
         	   <div class="container-fluid">
	                <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
	                	<span class="icon-bar"></span>
	                	<span class="icon-bar"></span>
	                	<span class="icon-bar"></span>
	                </a>


		         		<a href="#" class="brand">
		         			<!-- Viva PHP -->
		         		</a>
		         		<div class="nav-collapse">
			         		<ul class="nav">
			         			<li><a href="<?php echo Conection::route();?>">Home</a></li>
			         			<li><a href="">Quiénes Somos</a></li>
			         			<li><a href="<?php echo Conection::route();?>blog/">Blog</a></li>
			         			<li><a href="<?php echo Conection::route();?>eventos/">Eventos</a></li>

			         			<li class="dropdown">
			         				<a href="#" class="dropdown-toggle" data-toggle="dropdown">
			         				   #vivaPHP<i class="caret"></i>
			         				</a>
                                    <ul class="dropdown-menu">
                                    	 <li><a href=""><i class="icon-sunrise"></i> Quieres ayuda urgente</a></li>
			         			         <li><a href=""><i class="icon-help-3"></i> ¿Ya sabes las reglas?</a></li>
			         			         <li><a href=""><i class="icon-share-4"></i> ¿Que nos puedes compartir?</a></li>

                                    </ul>


			         			</li>
			         			<li><a href="<?php echo Conection::route();?>contacto/">Contacto</a></li>

                                <li class="search">
                                	<form action="" class="navbar-search pull-left">
	                                	 <div class="input-prepend">
											 <input type="text" placeholder="Digite su busqueda..." class="search-query span2">
	                                         <button type="submit">Buscar</button>
											</div>
									</form>

                               </li>
			         		</ul>


		         	    </div>
		         	        <div class="pull-right login">
			         			<i class="icon-user icon-white"></i>
			         			<a href="#myModal2" role="button" data-toggle="modal">Login</a>
			         		</div>


			      <!-- ********************************** -->
			         </div>
        	</div>
     </div>


